# Generated by Django 3.2.3 on 2022-04-20 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(choices=[('ORD', 'Ordering'), ('PRE', 'Preparing'), ('DEL', 'Delivering'), ('DED', 'Delivered')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('Adm', 'Admin'), ('Emp', 'Employee'), ('Cus', 'Customer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('toppings_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='total_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_created_time', models.DateTimeField()),
                ('time_of_delivery', models.DateTimeField()),
                ('delivery_completion', models.DateTimeField()),
                ('payment_received', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status_fk_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.order_status')),
                ('user_fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('reviews_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_description', models.TextField()),
                ('products_fk_products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.products')),
                ('users_fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment_proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_fk_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.profile')),
                ('total_order_fk_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.total_order')),
                ('users_fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('order_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_product_quantity', models.IntegerField()),
                ('order_topping_quantity', models.IntegerField()),
                ('products_fk_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.products')),
                ('toppings_fk_toppings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.toppings')),
                ('total_order_fk_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.total_order')),
            ],
        ),
    ]
