# Generated by Django 3.2.3 on 2022-05-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='products',
            field=models.ManyToManyField(related_name='Toppings', to='farm_coffee_app.Product'),
        ),
    ]
