# Generated by Django 3.2.3 on 2022-05-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0002_topping_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://drive.google.com/uc?export=view&id=1aj_vT5zjJlkdEQ_VcCsdnvpVBi-Fjwyb', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='products',
            field=models.ManyToManyField(related_name='toppings', to='farm_coffee_app.Product'),
        ),
    ]
