# Generated by Django 3.2.3 on 2022-05-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0003_auto_20220512_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_total_items', to='farm_coffee_app.profile'),
        ),
    ]
