# Generated by Django 3.2.3 on 2022-05-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='farm_coffee_app.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_created_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
