# Generated by Django 3.2.3 on 2022-05-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_topping_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
