# Generated by Django 3.2.3 on 2022-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0004_auto_20220421_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=0, upload_to='static/farm_coffee_app/images'),
        ),
    ]
