# Generated by Django 3.2.3 on 2022-05-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0005_auto_20220512_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.product'),
        ),
    ]
