# Generated by Django 3.2.3 on 2022-05-09 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm_coffee_app', '0007_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(choices=[('ORD', 'Ordering'), ('PRE', 'Preparing'), ('DEL', 'Delivering'), ('DED', 'Delivered')], max_length=50)),
                ('order_created_time', models.DateTimeField()),
                ('time_of_delivery', models.DateTimeField()),
                ('delivery_completion', models.DateTimeField()),
                ('payment_received', models.BooleanField()),
                ('cart', models.ManyToManyField(to='farm_coffee_app.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_order',
        ),
        migrations.DeleteModel(
            name='Order_Status',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='item',
        ),
        migrations.RemoveField(
            model_name='total_order',
            name='cart_fk_cart_id',
        ),
        migrations.RemoveField(
            model_name='total_order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.AlterField(
            model_name='payment_proof',
            name='total_order_fk_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_coffee_app.order'),
        ),
        migrations.DeleteModel(
            name='Total_Order',
        ),
    ]
