# Generated by Django 3.2.3 on 2022-04-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0009_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
