# Generated by Django 3.2.3 on 2022-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_coffee_app', '0012_products_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
